"""
src/engine.py
══════════════════════════════════════════════════════════════════════════════
Metric Computation Engine — Aadhaar Sentinel V2

V2 CHANGES FROM V1 (each annotated with # V2 comments inline):

  1. PNA DENOMINATOR FIX:
       Census 2011 est_pincode_pop → RGI-projected 2026 est_pincode_pop.
       Fixes systematic PNA undercount in high-growth cities.
       est_pincode_pop_lower and est_pincode_pop_upper also generated for
       updated uncertainty bounds.

  2. DISTRICT+STATE JOIN FIX:
       V1 grouped and merged on ["district"] only — silently wrong for
       repeated district names across states (e.g. Aurangabad: Maharashtra
       and Bihar). V2 uses ["district", "state"] throughout.

  3. DPR PRESERVED; DPR_v2 ADDED:
       DPR = demo_total / (bio_total + 1)  ← V1 formula, kept as primary.
       DPR_v2 = demo_total / (γ_d × P_i^{2026} + ε)  ← Paper B Eq. (2).
       Keeping V1 DPR ensures scoring.py, app.py, and existing tests are
       unchanged. DPR_v2 is an additive column for Paper B methodology.

  4. k-ANONYMITY FLAG:
       Privacy_Masked = True for PINcodes in districts with projected
       population < K_ANONYMITY_THRESHOLD. This is a FLAG ONLY here.
       Masking (dropping rows) is performed at Zenodo export time (Paper A §4),
       not inside the analysis pipeline.

PAPER MAPPINGS:
  Paper B §3.2 — TAI definition (Eq. 1), DPR_v2 definition (Eq. 2),
                  PNA definition (Eq. 3). Cite RGI 2020 for γ_d values.
  Paper B §6   — Mention district-only join bug was found and fixed in V2.
  Paper A §3   — This module generates the derived feature columns.
  Paper A §4   — k_anonymity_flag + Privacy_Masked documented here.

IMPORTANT NOTE ON scoring.py:
  add_population_uncertainty() currently computes:
      PNA_conservative = TAI / est_pincode_pop
      PNA_upper_bound  = TAI / (est_pincode_pop * POP_GROWTH_FACTOR_MAX)
  In V2, est_pincode_pop already reflects projected 2026 growth.
  Multiplying by POP_GROWTH_FACTOR_MAX double-counts growth.
  Update add_population_uncertainty() to use est_pincode_pop_lower/upper
  (generated by this module) instead.
"""

import logging

import numpy as np
import pandas as pd

from src import config
from src.projections import build_projected_population, load_rgi_csv

logger = logging.getLogger(__name__)

# ── Module constants ──────────────────────────────────────────────────────────
# ε prevents division-by-zero in DPR_v2 for static-population zones.
# Paper B §3.2: "where ε = 1e-5 prevents undefined behaviour..."
EPSILON: float = 1e-5


# ── Core function (signature unchanged from V1) ───────────────────────────────

def calculate_base_metrics(demo_pin, bio_pin, enr_pin, district_pop_df):
    """
    Merge aggregated UIDAI datasets and compute TAI, DPR, DPR_v2, and PNA.

    Parameters
    ----------
    demo_pin : DataFrame
        Pincode-level demographic updates. Columns: pincode, district, state, demo_total
    bio_pin : DataFrame
        Pincode-level biometric updates. Columns: pincode, district, state, bio_total
    enr_pin : DataFrame
        Pincode-level enrolments. Columns: pincode, district, state, enrol_total
    district_pop_df : DataFrame
        Raw Census 2011 CSV loaded by pipeline.py.
        Expected columns: 'District name', 'State name', 'Population'

    Returns
    -------
    DataFrame with all input columns plus:
        TAI, DPR, DPR_v2,
        PNA, est_pincode_pop, est_pincode_pop_lower, est_pincode_pop_upper,
        annual_growth_rate, growth_source,
        Privacy_Masked
    """

    # ── Step 1: Merge UIDAI frames (logic unchanged from V1) ─────────────
    df = (
        demo_pin
        .merge(bio_pin, on=["pincode", "district", "state"], how="outer")
        .merge(enr_pin, on=["pincode", "district", "state"], how="outer")
        .fillna(0)
    )

    # Clean PINCODE strings (V1 logic preserved)
    df["pincode"] = df["pincode"].astype(str).str.split(".").str[0].str.zfill(6)

    # Ensure consistent UPPERCASE text keys (loader.py already does this,
    # but defensive re-normalization prevents silent mismatches)
    df["district"] = df["district"].astype(str).str.upper().str.strip()
    df["state"] = df["state"].astype(str).str.upper().str.strip()

    # ── Step 2: TAI — Total Activity Index (Paper B Eq. 1) ───────────────
    # TAI_i = Enrolments_i + DemographicUpdates_i + BiometricUpdates_i
    df["TAI"] = df["demo_total"] + df["bio_total"] + df["enrol_total"]

    # ── Step 3: DPR V1 — kept as primary DPR (Paper B comparison baseline) ─
    # DPR_i = ΔT_demo / (ΔT_bio + 1)
    # Preserves backward-compatibility with scoring.py, app.py, and tests.
    df["DPR"] = df["demo_total"] / (df["bio_total"] + 1)

    # ── Step 4: Prepare Census data and apply RGI projections ────────────
    # V2: Both district AND state are normalized here. V1 only uppercased
    # district, leaving state casing inconsistent with UIDAI data.
    census = district_pop_df.rename(
        columns={"District name": "district", "State name": "state"}
    ).copy()
    census["district"] = census["district"].astype(str).str.upper().str.strip()
    census["state"] = census["state"].astype(str).str.upper().str.strip()

    rgi_df = load_rgi_csv(config.RGI_PATH)
    projected_df = build_projected_population(census, rgi_df)

    # ── Step 5: Pincode count per (district, state) ───────────────────────
    # V2 FIX: groupby on BOTH district and state. V1 used district alone,
    # which silently merged across states for repeated district names.
    pin_counts = (
        df.groupby(["district", "state"], as_index=False)["pincode"]
        .nunique()
        .rename(columns={"pincode": "pin_count"})
    )

    # ── Step 6: Merge projected population with pin counts ────────────────
    proj_cols = [
        "district",
        "state",
        config.PROJECTED_POP_COLUMN,         # Projected_2026
        config.PROJECTED_POP_LOWER_COLUMN,   # Projected_2026_lower
        config.PROJECTED_POP_UPPER_COLUMN,   # Projected_2026_upper
        config.POPULATION_COLUMN,            # Population (Census 2011, for fallback)
        "annual_growth_rate",
        "growth_source",
        "k_anonymity_flag",
    ]
    district_stats = pin_counts.merge(
        projected_df[proj_cols],
        on=["district", "state"],
        how="left",
    )

    # ── Step 7: Three-tier population fallback ────────────────────────────
    # A district can be missing from the Census data entirely (no match after
    # left join → all projection cols NaN). Fallback chain:
    #   1. RGI projected 2026 population   (best — most methodologically sound)
    #   2. Census 2011 raw population      (if district absent from projections)
    #   3. CENSUS_FALLBACK_POP constant    (last resort — always logged)
    for col in [
        config.PROJECTED_POP_COLUMN,
        config.PROJECTED_POP_LOWER_COLUMN,
        config.PROJECTED_POP_UPPER_COLUMN,
    ]:
        district_stats[col] = (
            district_stats[col]
            .fillna(district_stats[config.POPULATION_COLUMN])
            .fillna(config.CENSUS_FALLBACK_POP)
        )

    unmatched = district_stats[config.PROJECTED_POP_COLUMN] == config.CENSUS_FALLBACK_POP
    if unmatched.any():
        logger.warning(
            "%d districts could not be matched to any Census population. "
            "Using CENSUS_FALLBACK_POP = %d. "
            "Check district name consistency between UIDAI and Census CSVs.",
            int(unmatched.sum()),
            config.CENSUS_FALLBACK_POP,
        )

    district_stats["annual_growth_rate"] = (
        district_stats["annual_growth_rate"].fillna(config.NATIONAL_FALLBACK_RATE)
    )
    district_stats["growth_source"] = (
        district_stats["growth_source"].fillna("no_census_match")
    )
    district_stats["k_anonymity_flag"] = (
        district_stats["k_anonymity_flag"].fillna(False).astype(bool)
    )

    # ── Step 8: Per-PINCODE population proxy ─────────────────────────────
    # Proxy: district_projected_pop ÷ active PINcodes in district.
    # Documented limitation (Paper B §6): official PINCODE boundary shapefiles
    # are not publicly available in India; areal-weighted interpolation is
    # deferred to V3 pending data availability.
    district_stats["est_pincode_pop"] = (
        district_stats[config.PROJECTED_POP_COLUMN] / district_stats["pin_count"]
    )
    district_stats["est_pincode_pop_lower"] = (
        district_stats[config.PROJECTED_POP_LOWER_COLUMN] / district_stats["pin_count"]
    )
    district_stats["est_pincode_pop_upper"] = (
        district_stats[config.PROJECTED_POP_UPPER_COLUMN] / district_stats["pin_count"]
    )

    # ── Step 9: Merge district stats back into main dataframe ─────────────
    cols_to_merge = [
        "district",
        "state",
        "est_pincode_pop",
        "est_pincode_pop_lower",
        "est_pincode_pop_upper",
        "annual_growth_rate",
        "growth_source",
        "k_anonymity_flag",
    ]
    df = df.merge(district_stats[cols_to_merge], on=["district", "state"], how="left")

    # Ensure no NaN est_pincode_pop reaches downstream (would corrupt PNA silently)
    for pop_col in ["est_pincode_pop", "est_pincode_pop_lower", "est_pincode_pop_upper"]:
        df[pop_col] = df[pop_col].fillna(config.CENSUS_FALLBACK_POP)

    df["annual_growth_rate"] = df["annual_growth_rate"].fillna(config.NATIONAL_FALLBACK_RATE)

    # ── Step 10: PNA — Population-Normalised Activity (Paper B Eq. 3) ─────
    # PNA_i = TAI_i / P_i^{2026}
    # V2: denominator is RGI-projected 2026, not Census 2011.
    # replace(0, np.nan) prevents divide-by-zero without crashing the pipeline.
    df["PNA"] = df["TAI"] / df["est_pincode_pop"].replace(0, np.nan)

    # ── Step 11: DPR_v2 — RGI-normalized Demographic Pressure (Paper B Eq. 2)
    # DPR_v2_i = ΔT_demo / (γ_d × P_i^{2026} + ε)
    # Where γ_d = RGI annual growth rate for district d.
    # Interpretation: values >> 1 mean demographic updates far exceed expected
    # natural demographic activity — a process integrity signal.
    # NOTE: DPR (V1 formula) remains the PRIMARY scoring metric for continuity.
    df["DPR_v2"] = df["demo_total"] / (
        (df["annual_growth_rate"] * df["est_pincode_pop"]) + EPSILON
    )

    # ── Step 12: Privacy flag ─────────────────────────────────────────────
    # Privacy_Masked = True means this PINCODE's district had projected pop
    # below K_ANONYMITY_THRESHOLD. These rows should be excluded from the
    # Zenodo release of IndiaID-Bench (Paper A §4). They are NOT dropped here.
    df["Privacy_Masked"] = df["k_anonymity_flag"].fillna(False)
    df = df.drop(columns=["k_anonymity_flag"])

    # ── Step 13: Diagnostics ──────────────────────────────────────────────
    n_masked = int(df["Privacy_Masked"].sum())
    logger.info(
        "V2 engine complete | PINcodes: %d | DPR median: %.2f | "
        "PNA median: %.4f | Privacy_Masked: %d",
        len(df),
        df["DPR"].median(),
        df["PNA"].median(),
        n_masked,
    )
    if n_masked > 0:
        logger.info(
            "k-Anonymity note: %d PINcodes flagged. "
            "Filter 'Privacy_Masked == True' before Zenodo export.",
            n_masked,
        )

    return df